# Generated by Django 5.1 on 2025-04-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background_color',
            field=models.CharField(default='blue-600', max_length=50),
        ),
    ]
